### ISSUE TITLE
Support passing object instead of just JSDoc

### ISSUE THREAD

**Issue by Tzook** [myheritage/UiZoo.js#59]
UiZoo.init

**Comment by NoamELB** [comment]
supporting object like this: (copy-paste to console)

`JSON.parse('{
    "name": [
        {"title":"name","description":null,"name":"Menu"}
    ],
    "module":[
        {"title":"module","description":null,"type":null,"name":"Menus"}
    ],
    "description":[
        {"title":"description","description":"Menu description"}
    ],
    "example":[
        {"title":"example","description":"<Menu/>"}
    ],
    "param":[
        {"title":"param","description":"current selected value of MenuItem inside the menu","type":{"type":"OptionalType","expression":{"type":"UnionType","elements":[{"type":"NameExpression","name":"string"},{"type":"NameExpression","name":"number"}]}},"name":"value"},
        {"title":"param","description":"callback for changes in selected value","type":{"type":"OptionalType","expression":{"type":"NameExpression","name":"function"}},"name":"onChange"},
        {"title":"param","description":"MenuItems to be selected","type":{"type":"NameExpression","name":"node"},"name":"children"}
    ]
}');`

**Comment by NoamELB** [comment]
additional changes may be done here:
https://github.com/myheritage/UiZoo.js/blob/develop/client/services/parseDocumentation.js#L20
