### ISSUE TITLE
Source code doesn't show properly

### ISSUE THREAD

**Issue by JamesSingleton** [myheritage/UiZoo.js#73]
Hello,

This might not be the place to put this, however, recently I ran uizoo on a basic create-react-app application and ran into an issue while viewing UiZoo. When I look at the documentation I see something like

```
<RaisedButton onClick={...}>
  Raised Button Text
</RaisedButton>
```

However, when I run it on a create-react-app project I get something like:

```
<t onClick={...}>
  Raised Button Text
</t>
```

I am not sure what is exactly causing this as I don't get any error messages.

This is what my button.js code looks like

```
import React from 'react';

/**
 * @name 
 * TestButton
 * 
 * @module
 * Inputs
 * 
 * @description
 * A styled button for clicking and hovering
 * 
 * @example
 * <TestButton onClick={(e) => console.log('TestButton was clicked, event: ', e)}>
 *    Raised Button Text
 * </TestButton>
 * 
 * @param {function} [onClick] callback for the tooltip was clicked
 * @param {node} children the clickable element that will open the tooltip
 */
export default class TestButton extends React.Component {
  render() {
    const {children, onClick} = this.props;
    return (
      <div>
        <button 
          tabIndex="1"
          onClick={e => onClick && onClick(e)}>
          <span>{children}</span>
        </button>
      </div>
    );
  }
}
```

Any help would be greatly appreciated. If this doesn't work with create-react-app, some examples of what it does work with would be greatly appreciated.

**Comment by JamesSingleton** [comment]
@liorgreenb I saw you self-assigned this to yourself, any idea on what might be causing this?

**Comment by liorgreenb** [comment]
I'll be checking the problem this week, is your bundle minified my any chance?

**Comment by JamesSingleton** [comment]
@liorgreenb all I did was run it on a brand new create-react-app. So my guess is not my bundle was not minified as I did not run npm build. Does that need to happen before UiZoo can run?

**Comment by JamesSingleton** [comment]
@liorgreenb , any update/anything I can help with?

**Comment by mbarzeev** [comment]
Hi @JamesSingleton,
It seems that the Webpack "no-configuration" feature messed with out bundling a bit ;) The default falls to "production" mode when no mode is defined. We will fix this in the coming build, but in the meantime here is a quick solution for you:
Under your project root directory the is now a .uizoo-app directory. Residing in it is a file called "webpack.uizoo.js" which holds the Webpack configuration (BTW - here you can override or customise your own Webpack preferences). In this file, please add the mode for Webpack. You can either set it to 'none' (which means that no defaults will be taken) or to 'development. Read more about it [here](https://webpack.js.org/concepts/mode/). 
Here is how it should be after you change it:
```
const webpackConfig = {
    mode: 'none',
    devtool: 'cheap-module-source-map',
    entry: {
        app: [path.join(__dirname, 'index.js')]
    },
    ...
```
Now run uizoo again and see if that solves your issue - and update this thread with the results :)

Cheers
