### ISSUE TITLE
Allow for imports in examples

### ISSUE THREAD

**Issue by th3fallen** [myheritage/UiZoo.js#76]
if this is already possible im sorry but i cant find a good way, we have modal components that are split into three components (Modal, ModalBody, ModalHeader) how would one do an example that used all three to show a "Modal" example?

**Comment by liorgreenb** [comment]
@th3fallen 
Hey (:
If the components are also available through UiZoo you can use them directly in the example JSX and they will work automatically.

For example, the components you mentioned, consider jsdoc for Modal
`
@example
<Modal>
    <ModalHeader>Header</ModalHeader>
    <ModalBody>Body</ModalNodu
</Modal>
`

**Comment by th3fallen** [comment]
Excellent! thanks for the quick response.
